from __future__ import annotations

from typing import Any

ENDPOINT_CATALOG: list[dict[str, Any]] = [
    # ── Auth ──────────────────────────────────────────────────────────────
    {
        "name": "exchange_code_for_token",
        "method": "POST",
        "path": "/api/v2/auth/token/get",
        "description": "Exchange OAuth code for access_token and refresh_token",
        "family": "Auth",
        "auth_required": False,
    },
    {
        "name": "refresh_token",
        "method": "POST",
        "path": "/api/v2/auth/access_token/get",
        "description": "Refresh access_token using refresh_token",
        "family": "Auth",
        "auth_required": False,
    },
    # ── Shop ──────────────────────────────────────────────────────────────
    {
        "name": "get_shop_info",
        "method": "GET",
        "path": "/api/v2/shop/get_shop_info",
        "description": "Get basic shop info",
        "family": "Shop",
        "auth_required": True,
    },
    {
        "name": "update_shop_profile",
        "method": "POST",
        "path": "/api/v2/shop/update_profile",
        "description": "Update shop profile (name, logo, description)",
        "family": "Shop",
        "auth_required": True,
    },
    {
        "name": "get_warehouse_detail",
        "method": "GET",
        "path": "/api/v2/shop/get_warehouse_detail",
        "description": "Get warehouse detail",
        "family": "Shop",
        "auth_required": True,
    },
    {
        "name": "get_shop_notification",
        "method": "GET",
        "path": "/api/v2/shop/get_shop_notification",
        "description": "Get shop notifications",
        "family": "Shop",
        "auth_required": True,
    },
    {
        "name": "get_authorised_reseller_brand",
        "method": "GET",
        "path": "/api/v2/shop/get_authorised_reseller_brand",
        "description": "Get authorised reseller brands",
        "family": "Shop",
        "auth_required": True,
    },
    {
        "name": "get_shop_holiday_mode",
        "method": "GET",
        "path": "/api/v2/shop/get_shop_holiday_mode",
        "description": "Get shop holiday mode setting",
        "family": "Shop",
        "auth_required": True,
    },
    {
        "name": "set_shop_holiday_mode",
        "method": "POST",
        "path": "/api/v2/shop/set_shop_holiday_mode",
        "description": "Set shop holiday mode on/off",
        "family": "Shop",
        "auth_required": True,
    },
    {
        "name": "get_br_shop_onboarding_info",
        "method": "GET",
        "path": "/api/v2/shop/get_br_shop_onboarding_info",
        "description": "Get Brazil shop onboarding info",
        "family": "Shop",
        "auth_required": True,
    },
    # ── Product ───────────────────────────────────────────────────────────
    {
        "name": "get_item_list",
        "method": "GET",
        "path": "/api/v2/product/get_item_list",
        "description": "List items with pagination (offset/page_size)",
        "family": "Product",
        "auth_required": True,
    },
    {
        "name": "get_item_detail",
        "method": "GET",
        "path": "/api/v2/product/get_item_detail",
        "description": "Get full item detail",
        "family": "Product",
        "auth_required": True,
    },
    {
        "name": "get_item_base_info",
        "method": "GET",
        "path": "/api/v2/product/get_item_base_info",
        "description": "Get basic item info",
        "family": "Product",
        "auth_required": True,
    },
    {
        "name": "get_item_variations",
        "method": "GET",
        "path": "/api/v2/product/get_item_variations",
        "description": "Get item variations/SKUs",
        "family": "Product",
        "auth_required": True,
    },
    {
        "name": "update_item_stock",
        "method": "POST",
        "path": "/api/v2/product/update_stock",
        "description": "Update item or variation stock",
        "family": "Product",
        "auth_required": True,
    },
    {
        "name": "update_item_price",
        "method": "POST",
        "path": "/api/v2/product/update_price",
        "description": "Update item or variation price",
        "family": "Product",
        "auth_required": True,
    },
    {
        "name": "get_item_performance",
        "method": "GET",
        "path": "/api/v2/product/get_item_performance",
        "description": "Get item performance metrics",
        "family": "Product",
        "auth_required": True,
    },
    {
        "name": "add_item",
        "method": "POST",
        "path": "/api/v2/product/add_item",
        "description": "Create a new item",
        "family": "Product",
        "auth_required": True,
    },
    {
        "name": "update_item",
        "method": "POST",
        "path": "/api/v2/product/update_item",
        "description": "Update an existing item",
        "family": "Product",
        "auth_required": True,
    },
    {
        "name": "delete_item",
        "method": "POST",
        "path": "/api/v2/product/delete_item",
        "description": "Delete an item",
        "family": "Product",
        "auth_required": True,
    },
    {
        "name": "unlist_item",
        "method": "POST",
        "path": "/api/v2/product/unlist_item",
        "description": "Unlist or re-list an item",
        "family": "Product",
        "auth_required": True,
    },
    {
        "name": "get_category",
        "method": "GET",
        "path": "/api/v2/product/get_category",
        "description": "Get product categories",
        "family": "Product",
        "auth_required": True,
    },
    {
        "name": "get_attribute_tree",
        "method": "GET",
        "path": "/api/v2/product/get_attribute_tree",
        "description": "Get attribute tree for a category",
        "family": "Product",
        "auth_required": True,
    },
    {
        "name": "get_brand_list",
        "method": "GET",
        "path": "/api/v2/product/get_brand_list",
        "description": "Get brand list for a category",
        "family": "Product",
        "auth_required": True,
    },
    {
        "name": "get_comment",
        "method": "GET",
        "path": "/api/v2/product/get_comment",
        "description": "Get item comments",
        "family": "Product",
        "auth_required": True,
    },
    {
        "name": "reply_comment",
        "method": "POST",
        "path": "/api/v2/product/reply_comment",
        "description": "Reply to an item comment",
        "family": "Product",
        "auth_required": True,
    },
    {
        "name": "boost_item",
        "method": "POST",
        "path": "/api/v2/product/boost_item",
        "description": "Boost items in search results",
        "family": "Product",
        "auth_required": True,
    },
    {
        "name": "search_item",
        "method": "GET",
        "path": "/api/v2/product/search_item",
        "description": "Search items by name",
        "family": "Product",
        "auth_required": True,
    },
    {
        "name": "get_item_extra_info",
        "method": "GET",
        "path": "/api/v2/product/get_item_extra_info",
        "description": "Get extra info for items",
        "family": "Product",
        "auth_required": True,
    },
    {
        "name": "get_item_limit",
        "method": "GET",
        "path": "/api/v2/product/get_item_limit",
        "description": "Get item listing limit",
        "family": "Product",
        "auth_required": True,
    },
    {
        "name": "get_item_promotion",
        "method": "GET",
        "path": "/api/v2/product/get_item_promotion",
        "description": "Get item promotion info",
        "family": "Product",
        "auth_required": True,
    },
    {
        "name": "get_item_violation_info",
        "method": "GET",
        "path": "/api/v2/product/get_item_violation_info",
        "description": "Get item violation info",
        "family": "Product",
        "auth_required": True,
    },
    # ── GlobalProduct ─────────────────────────────────────────────────────
    {
        "name": "get_global_item_list",
        "method": "GET",
        "path": "/api/v2/global_product/get_global_item_list",
        "description": "List global items",
        "family": "GlobalProduct",
        "auth_required": True,
    },
    {
        "name": "add_global_item",
        "method": "POST",
        "path": "/api/v2/global_product/add_global_item",
        "description": "Add a global item",
        "family": "GlobalProduct",
        "auth_required": True,
    },
    {
        "name": "get_global_item_detail",
        "method": "GET",
        "path": "/api/v2/global_product/get_global_item_detail",
        "description": "Get global item detail",
        "family": "GlobalProduct",
        "auth_required": True,
    },
    {
        "name": "update_global_item",
        "method": "POST",
        "path": "/api/v2/global_product/update_global_item",
        "description": "Update a global item",
        "family": "GlobalProduct",
        "auth_required": True,
    },
    {
        "name": "delete_global_item",
        "method": "POST",
        "path": "/api/v2/global_product/delete_global_item",
        "description": "Delete a global item",
        "family": "GlobalProduct",
        "auth_required": True,
    },
    # ── Order ─────────────────────────────────────────────────────────────
    {
        "name": "get_order_list",
        "method": "GET",
        "path": "/api/v2/order/get_order_list",
        "description": "List orders by time window and cursor",
        "family": "Order",
        "auth_required": True,
    },
    {
        "name": "get_order_detail",
        "method": "GET",
        "path": "/api/v2/order/get_order_detail",
        "description": "Get full order detail",
        "family": "Order",
        "auth_required": True,
    },
    {
        "name": "split_order",
        "method": "POST",
        "path": "/api/v2/order/split_order",
        "description": "Split order into packages",
        "family": "Order",
        "auth_required": True,
    },
    {
        "name": "cancel_order",
        "method": "POST",
        "path": "/api/v2/order/cancel_order",
        "description": "Cancel an order",
        "family": "Order",
        "auth_required": True,
    },
    {
        "name": "get_order_address",
        "method": "GET",
        "path": "/api/v2/order/get_order_address",
        "description": "Get order shipping address",
        "family": "Order",
        "auth_required": True,
    },
    # ── Logistics ─────────────────────────────────────────────────────────
    {
        "name": "get_logistics_channel_list",
        "method": "GET",
        "path": "/api/v2/logistics/get_channel_list",
        "description": "List available logistics channels",
        "family": "Logistics",
        "auth_required": True,
    },
    {
        "name": "get_logistics_info",
        "method": "GET",
        "path": "/api/v2/logistics/get_logistics_info",
        "description": "Get logistics info for an order",
        "family": "Logistics",
        "auth_required": True,
    },
    {
        "name": "get_tracking_number",
        "method": "GET",
        "path": "/api/v2/logistics/get_tracking_number",
        "description": "Get tracking number for an order",
        "family": "Logistics",
        "auth_required": True,
    },
    {
        "name": "ship_order",
        "method": "POST",
        "path": "/api/v2/logistics/ship_order",
        "description": "Mark order as shipped",
        "family": "Logistics",
        "auth_required": True,
    },
    {
        "name": "get_shipping_parameter",
        "method": "GET",
        "path": "/api/v2/logistics/get_shipping_parameter",
        "description": "Get shipping parameters for an order",
        "family": "Logistics",
        "auth_required": True,
    },
    {
        "name": "get_tracking_list",
        "method": "GET",
        "path": "/api/v2/logistics/get_tracking_list",
        "description": "Get tracking list for an order",
        "family": "Logistics",
        "auth_required": True,
    },
    {
        "name": "get_waybill",
        "method": "GET",
        "path": "/api/v2/logistics/get_waybill",
        "description": "Get waybill for an order package",
        "family": "Logistics",
        "auth_required": True,
    },
    {
        "name": "get_address_list",
        "method": "GET",
        "path": "/api/v2/logistics/get_address_list",
        "description": "Get logistics address list",
        "family": "Logistics",
        "auth_required": True,
    },
    # ── Payment ───────────────────────────────────────────────────────────
    {
        "name": "get_escrow_detail",
        "method": "GET",
        "path": "/api/v2/payment/get_escrow_detail",
        "description": "Get escrow detail for an order",
        "family": "Payment",
        "auth_required": True,
    },
    {
        "name": "get_escrow_list",
        "method": "GET",
        "path": "/api/v2/payment/get_escrow_list",
        "description": "List escrow transactions",
        "family": "Payment",
        "auth_required": True,
    },
    {
        "name": "get_escrow_detail_batch",
        "method": "POST",
        "path": "/api/v2/payment/get_escrow_detail_batch",
        "description": "Batch get escrow details",
        "family": "Payment",
        "auth_required": True,
    },
    {
        "name": "get_wallet_transaction_list",
        "method": "GET",
        "path": "/api/v2/payment/get_wallet_transaction_list",
        "description": "List wallet transactions",
        "family": "Payment",
        "auth_required": True,
    },
    {
        "name": "generate_income_report",
        "method": "POST",
        "path": "/api/v2/payment/generate_income_report",
        "description": "Generate an income report",
        "family": "Payment",
        "auth_required": True,
    },
    {
        "name": "get_income_report",
        "method": "GET",
        "path": "/api/v2/payment/get_income_report",
        "description": "Get an income report by ID",
        "family": "Payment",
        "auth_required": True,
    },
    {
        "name": "get_payout_info",
        "method": "GET",
        "path": "/api/v2/payment/get_payout_info",
        "description": "Get payout information",
        "family": "Payment",
        "auth_required": True,
    },
    # ── Discount ──────────────────────────────────────────────────────────
    {
        "name": "get_discount_list",
        "method": "GET",
        "path": "/api/v2/discount/get_discount_list",
        "description": "List discount campaigns by status",
        "family": "Discount",
        "auth_required": True,
    },
    {
        "name": "add_discount",
        "method": "POST",
        "path": "/api/v2/discount/add_discount",
        "description": "Add a discount campaign",
        "family": "Discount",
        "auth_required": True,
    },
    {
        "name": "update_discount",
        "method": "POST",
        "path": "/api/v2/discount/update_discount",
        "description": "Update a discount campaign",
        "family": "Discount",
        "auth_required": True,
    },
    {
        "name": "add_discount_item",
        "method": "POST",
        "path": "/api/v2/discount/add_discount_item",
        "description": "Add items to a discount campaign",
        "family": "Discount",
        "auth_required": True,
    },
    {
        "name": "remove_discount_item",
        "method": "POST",
        "path": "/api/v2/discount/remove_discount_item",
        "description": "Remove items from a discount campaign",
        "family": "Discount",
        "auth_required": True,
    },
    # ── Voucher ───────────────────────────────────────────────────────────
    {
        "name": "get_voucher_list",
        "method": "GET",
        "path": "/api/v2/voucher/get_voucher_list",
        "description": "List vouchers by status",
        "family": "Voucher",
        "auth_required": True,
    },
    {
        "name": "add_voucher",
        "method": "POST",
        "path": "/api/v2/voucher/add_voucher",
        "description": "Add a voucher",
        "family": "Voucher",
        "auth_required": True,
    },
    {
        "name": "update_voucher",
        "method": "POST",
        "path": "/api/v2/voucher/update_voucher",
        "description": "Update a voucher",
        "family": "Voucher",
        "auth_required": True,
    },
    {
        "name": "delete_voucher",
        "method": "POST",
        "path": "/api/v2/voucher/delete_voucher",
        "description": "Delete a voucher",
        "family": "Voucher",
        "auth_required": True,
    },
    # ── Bundle Deal ───────────────────────────────────────────────────────
    {
        "name": "get_bundle_deal_list",
        "method": "GET",
        "path": "/api/v2/bundle_deal/get_bundle_deal_list",
        "description": "List bundle deal campaigns",
        "family": "BundleDeal",
        "auth_required": True,
    },
    {
        "name": "add_bundle_deal",
        "method": "POST",
        "path": "/api/v2/bundle_deal/add_bundle_deal",
        "description": "Add a bundle deal campaign",
        "family": "BundleDeal",
        "auth_required": True,
    },
    {
        "name": "update_bundle_deal",
        "method": "POST",
        "path": "/api/v2/bundle_deal/update_bundle_deal",
        "description": "Update a bundle deal campaign",
        "family": "BundleDeal",
        "auth_required": True,
    },
    {
        "name": "delete_bundle_deal",
        "method": "POST",
        "path": "/api/v2/bundle_deal/delete_bundle_deal",
        "description": "Delete a bundle deal campaign",
        "family": "BundleDeal",
        "auth_required": True,
    },
    # ── Add-On Deal ───────────────────────────────────────────────────────
    {
        "name": "get_add_on_deal_list",
        "method": "GET",
        "path": "/api/v2/add_on_deal/get_add_on_deal_list",
        "description": "List add-on deal campaigns",
        "family": "AddOnDeal",
        "auth_required": True,
    },
    {
        "name": "add_add_on_deal",
        "method": "POST",
        "path": "/api/v2/add_on_deal/add_add_on_deal",
        "description": "Add an add-on deal campaign",
        "family": "AddOnDeal",
        "auth_required": True,
    },
    {
        "name": "update_add_on_deal",
        "method": "POST",
        "path": "/api/v2/add_on_deal/update_add_on_deal",
        "description": "Update an add-on deal campaign",
        "family": "AddOnDeal",
        "auth_required": True,
    },
    # ── Returns ───────────────────────────────────────────────────────────
    {
        "name": "get_return_list",
        "method": "GET",
        "path": "/api/v2/returns/get_return_list",
        "description": "List returns/refunds by time window",
        "family": "Returns",
        "auth_required": True,
    },
    {
        "name": "get_return_detail",
        "method": "GET",
        "path": "/api/v2/returns/get_return_detail",
        "description": "Get return/refund detail",
        "family": "Returns",
        "auth_required": True,
    },
    {
        "name": "confirm_return",
        "method": "POST",
        "path": "/api/v2/returns/confirm_return",
        "description": "Confirm or process a return",
        "family": "Returns",
        "auth_required": True,
    },
    {
        "name": "dispute_return",
        "method": "POST",
        "path": "/api/v2/returns/dispute_return",
        "description": "Dispute a return",
        "family": "Returns",
        "auth_required": True,
    },
    # ── Chat ──────────────────────────────────────────────────────────────
    {
        "name": "send_chat_message",
        "method": "POST",
        "path": "/api/v2/chat/send_message",
        "description": "Send a chat message to a buyer",
        "family": "Chat",
        "auth_required": True,
    },
    {
        "name": "get_chat_history",
        "method": "GET",
        "path": "/api/v2/chat/get_history",
        "description": "Get chat history for a conversation",
        "family": "Chat",
        "auth_required": True,
    },
    {
        "name": "get_conversation_list",
        "method": "GET",
        "path": "/api/v2/chat/get_conversation_list",
        "description": "List conversations",
        "family": "Chat",
        "auth_required": True,
    },
    {
        "name": "pin_conversation",
        "method": "POST",
        "path": "/api/v2/chat/pin_conversation",
        "description": "Pin or unpin a conversation",
        "family": "Chat",
        "auth_required": True,
    },
    {
        "name": "read_conversation",
        "method": "POST",
        "path": "/api/v2/chat/read_conversation",
        "description": "Mark conversation as read",
        "family": "Chat",
        "auth_required": True,
    },
    # ── MediaSpace ────────────────────────────────────────────────────────
    {
        "name": "init_video_upload",
        "method": "POST",
        "path": "/api/v2/media_space/init_video_upload",
        "description": "Initialize a video upload",
        "family": "MediaSpace",
        "auth_required": True,
    },
    {
        "name": "get_video_upload_result",
        "method": "GET",
        "path": "/api/v2/media_space/get_video_upload_result",
        "description": "Get video upload result",
        "family": "MediaSpace",
        "auth_required": True,
    },
    {
        "name": "upload_video_part",
        "method": "POST",
        "path": "/api/v2/media_space/upload_video_part",
        "description": "Upload a video part",
        "family": "MediaSpace",
        "auth_required": True,
    },
    {
        "name": "complete_video_upload",
        "method": "POST",
        "path": "/api/v2/media_space/complete_video_upload",
        "description": "Complete a video upload",
        "family": "MediaSpace",
        "auth_required": True,
    },
    # ── Media ─────────────────────────────────────────────────────────────
    {
        "name": "upload_image",
        "method": "POST",
        "path": "/api/v2/media/upload_image",
        "description": "Upload an image from URL",
        "family": "Media",
        "auth_required": True,
    },
    # ── Ads ───────────────────────────────────────────────────────────────
    {
        "name": "create_campaign",
        "method": "POST",
        "path": "/api/v2/ads/create_campaign",
        "description": "Create an ad campaign",
        "family": "Ads",
        "auth_required": True,
    },
    {
        "name": "update_campaign",
        "method": "POST",
        "path": "/api/v2/ads/update_campaign",
        "description": "Update an ad campaign",
        "family": "Ads",
        "auth_required": True,
    },
    {
        "name": "create_ad_group",
        "method": "POST",
        "path": "/api/v2/ads/create_ad_group",
        "description": "Create an ad group",
        "family": "Ads",
        "auth_required": True,
    },
    {
        "name": "update_ad_group",
        "method": "POST",
        "path": "/api/v2/ads/update_ad_group",
        "description": "Update an ad group",
        "family": "Ads",
        "auth_required": True,
    },
    {
        "name": "get_ad_report",
        "method": "GET",
        "path": "/api/v2/ads/get_ad_report",
        "description": "Get ad performance report",
        "family": "Ads",
        "auth_required": True,
    },
    {
        "name": "get_campaign_list",
        "method": "GET",
        "path": "/api/v2/ads/get_campaign_list",
        "description": "List ad campaigns",
        "family": "Ads",
        "auth_required": True,
    },
    # ── AMS (Affiliate Marketing Solutions) ───────────────────────────────
    {
        "name": "get_ams_campaign_list",
        "method": "GET",
        "path": "/api/v2/ams/get_campaign_list",
        "description": "List AMS campaigns",
        "family": "AMS",
        "auth_required": True,
    },
    {
        "name": "get_ams_report",
        "method": "GET",
        "path": "/api/v2/ams/get_report",
        "description": "Get AMS performance report",
        "family": "AMS",
        "auth_required": True,
    },
    {
        "name": "create_ams_campaign",
        "method": "POST",
        "path": "/api/v2/ams/create_campaign",
        "description": "Create an AMS campaign",
        "family": "AMS",
        "auth_required": True,
    },
    {
        "name": "update_ams_campaign",
        "method": "POST",
        "path": "/api/v2/ams/update_campaign",
        "description": "Update an AMS campaign",
        "family": "AMS",
        "auth_required": True,
    },
    # ── Account Health ────────────────────────────────────────────────────
    {
        "name": "get_shop_performance",
        "method": "GET",
        "path": "/api/v2/account_health/get_shop_performance",
        "description": "Get shop performance metrics",
        "family": "AccountHealth",
        "auth_required": True,
    },
    {
        "name": "get_penalty_point_history",
        "method": "GET",
        "path": "/api/v2/account_health/get_penalty_point_history",
        "description": "Get penalty point history",
        "family": "AccountHealth",
        "auth_required": True,
    },
    {
        "name": "get_punishment_history",
        "method": "GET",
        "path": "/api/v2/account_health/get_punishment_history",
        "description": "Get punishment history",
        "family": "AccountHealth",
        "auth_required": True,
    },
    {
        "name": "get_listings_with_issues",
        "method": "GET",
        "path": "/api/v2/account_health/get_listings_with_issues",
        "description": "Get listings with issues",
        "family": "AccountHealth",
        "auth_required": True,
    },
    {
        "name": "get_late_orders",
        "method": "GET",
        "path": "/api/v2/account_health/get_late_orders",
        "description": "Get late orders",
        "family": "AccountHealth",
        "auth_required": True,
    },
    {
        "name": "get_metric_source_detail",
        "method": "GET",
        "path": "/api/v2/account_health/get_metric_source_detail",
        "description": "Get metric source detail",
        "family": "AccountHealth",
        "auth_required": True,
    },
    # ── Flash Sale ────────────────────────────────────────────────────────
    {
        "name": "add_flash_sale",
        "method": "POST",
        "path": "/api/v2/shop_flash_sale/add_flash_sale",
        "description": "Add a flash sale campaign",
        "family": "FlashSale",
        "auth_required": True,
    },
    {
        "name": "update_flash_sale",
        "method": "POST",
        "path": "/api/v2/shop_flash_sale/update_flash_sale",
        "description": "Update a flash sale campaign",
        "family": "FlashSale",
        "auth_required": True,
    },
    {
        "name": "get_flash_sale_list",
        "method": "GET",
        "path": "/api/v2/shop_flash_sale/get_flash_sale_list",
        "description": "List flash sale campaigns",
        "family": "FlashSale",
        "auth_required": True,
    },
    # ── Top Picks ─────────────────────────────────────────────────────────
    {
        "name": "add_top_picks",
        "method": "POST",
        "path": "/api/v2/top_picks/add_top_picks",
        "description": "Add a top picks collection",
        "family": "TopPicks",
        "auth_required": True,
    },
    {
        "name": "update_top_picks",
        "method": "POST",
        "path": "/api/v2/top_picks/update_top_picks",
        "description": "Update a top picks collection",
        "family": "TopPicks",
        "auth_required": True,
    },
    {
        "name": "get_top_picks_list",
        "method": "GET",
        "path": "/api/v2/top_picks/get_top_picks_list",
        "description": "List top picks collections",
        "family": "TopPicks",
        "auth_required": True,
    },
    # ── First Mile ────────────────────────────────────────────────────────
    {
        "name": "get_first_mile_tracking_number",
        "method": "GET",
        "path": "/api/v2/first_mile/get_tracking_number",
        "description": "Get first mile tracking number",
        "family": "FirstMile",
        "auth_required": True,
    },
    {
        "name": "get_first_mile_waybill",
        "method": "GET",
        "path": "/api/v2/first_mile/get_waybill",
        "description": "Get first mile waybill",
        "family": "FirstMile",
        "auth_required": True,
    },
    # ── Livestream ────────────────────────────────────────────────────────
    {
        "name": "create_livestream_session",
        "method": "POST",
        "path": "/api/v2/livestream/create_session",
        "description": "Create a livestream session",
        "family": "Livestream",
        "auth_required": True,
    },
    {
        "name": "get_livestream_session_list",
        "method": "GET",
        "path": "/api/v2/livestream/get_session_list",
        "description": "List livestream sessions",
        "family": "Livestream",
        "auth_required": True,
    },
    {
        "name": "update_livestream_session",
        "method": "POST",
        "path": "/api/v2/livestream/update_session",
        "description": "Update a livestream session",
        "family": "Livestream",
        "auth_required": True,
    },
    {
        "name": "delete_livestream_session",
        "method": "POST",
        "path": "/api/v2/livestream/delete_session",
        "description": "Delete a livestream session",
        "family": "Livestream",
        "auth_required": True,
    },
    {
        "name": "get_livestream_session_metrics",
        "method": "GET",
        "path": "/api/v2/livestream/get_session_metrics",
        "description": "Get livestream session metrics",
        "family": "Livestream",
        "auth_required": True,
    },
    # ── Video ─────────────────────────────────────────────────────────────
    {
        "name": "get_video_list",
        "method": "GET",
        "path": "/api/v2/video/get_video_list",
        "description": "List videos",
        "family": "Video",
        "auth_required": True,
    },
    {
        "name": "delete_video",
        "method": "POST",
        "path": "/api/v2/video/delete_video",
        "description": "Delete a video",
        "family": "Video",
        "auth_required": True,
    },
    {
        "name": "post_video",
        "method": "POST",
        "path": "/api/v2/video/post_video",
        "description": "Post a video from URL",
        "family": "Video",
        "auth_required": True,
    },
    {
        "name": "update_video",
        "method": "POST",
        "path": "/api/v2/video/update_video",
        "description": "Update a video",
        "family": "Video",
        "auth_required": True,
    },
    {
        "name": "get_video_analytics",
        "method": "GET",
        "path": "/api/v2/video/get_video_analytics",
        "description": "Get video analytics",
        "family": "Video",
        "auth_required": True,
    },
    # ── FBS (Fulfillment by Shopee) ───────────────────────────────────────
    {
        "name": "get_fbs_order_list",
        "method": "GET",
        "path": "/api/v2/fbs/get_order_list",
        "description": "List FBS orders",
        "family": "FBS",
        "auth_required": True,
    },
    {
        "name": "confirm_fbs_order",
        "method": "POST",
        "path": "/api/v2/fbs/confirm_order",
        "description": "Confirm an FBS order",
        "family": "FBS",
        "auth_required": True,
    },
    {
        "name": "ship_fbs_order",
        "method": "POST",
        "path": "/api/v2/fbs/ship_order",
        "description": "Ship an FBS order",
        "family": "FBS",
        "auth_required": True,
    },
    # ── Follow Prize ──────────────────────────────────────────────────────
    {
        "name": "add_follow_prize",
        "method": "POST",
        "path": "/api/v2/follow_prize/add_follow_prize",
        "description": "Add a follow prize campaign",
        "family": "FollowPrize",
        "auth_required": True,
    },
    {
        "name": "update_follow_prize",
        "method": "POST",
        "path": "/api/v2/follow_prize/update_follow_prize",
        "description": "Update a follow prize campaign",
        "family": "FollowPrize",
        "auth_required": True,
    },
    {
        "name": "get_follow_prize_list",
        "method": "GET",
        "path": "/api/v2/follow_prize/get_follow_prize_list",
        "description": "List follow prize campaigns",
        "family": "FollowPrize",
        "auth_required": True,
    },
    {
        "name": "delete_follow_prize",
        "method": "POST",
        "path": "/api/v2/follow_prize/delete_follow_prize",
        "description": "Delete a follow prize campaign",
        "family": "FollowPrize",
        "auth_required": True,
    },
    # ── Shop Category ─────────────────────────────────────────────────────
    {
        "name": "add_shop_category",
        "method": "POST",
        "path": "/api/v2/shop_category/add_shop_category",
        "description": "Add a shop category",
        "family": "ShopCategory",
        "auth_required": True,
    },
    {
        "name": "update_shop_category",
        "method": "POST",
        "path": "/api/v2/shop_category/update_shop_category",
        "description": "Update a shop category",
        "family": "ShopCategory",
        "auth_required": True,
    },
    {
        "name": "delete_shop_category",
        "method": "POST",
        "path": "/api/v2/shop_category/delete_shop_category",
        "description": "Delete a shop category",
        "family": "ShopCategory",
        "auth_required": True,
    },
    {
        "name": "get_shop_category_list",
        "method": "GET",
        "path": "/api/v2/shop_category/get_shop_category_list",
        "description": "List shop categories",
        "family": "ShopCategory",
        "auth_required": True,
    },
    # ── Push (Webhooks) ───────────────────────────────────────────────────
    {
        "name": "get_push_config",
        "method": "GET",
        "path": "/api/v2/push/get_push_config",
        "description": "Get push notification config",
        "family": "Push",
        "auth_required": True,
    },
    {
        "name": "set_push_config",
        "method": "POST",
        "path": "/api/v2/push/set_push_config",
        "description": "Set push notification config",
        "family": "Push",
        "auth_required": True,
    },
    # ── Merchant ──────────────────────────────────────────────────────────
    {
        "name": "get_merchant_info",
        "method": "GET",
        "path": "/api/v2/merchant/get_merchant_info",
        "description": "Get merchant info",
        "family": "Merchant",
        "auth_required": True,
    },
    {
        "name": "get_shop_list_by_merchant",
        "method": "GET",
        "path": "/api/v2/merchant/get_shop_list_by_merchant",
        "description": "Get shop list by merchant",
        "family": "Merchant",
        "auth_required": True,
    },
    # ── Public (No Auth) ──────────────────────────────────────────────────
    {
        "name": "get_shops_by_partner",
        "method": "GET",
        "path": "/api/v2/public/get_shops_by_partner",
        "description": "Get shops by partner ID",
        "family": "Public",
        "auth_required": True,
    },
    {
        "name": "get_public_categories",
        "method": "GET",
        "path": "/api/v2/public/get_category",
        "description": "Get public categories",
        "family": "Public",
        "auth_required": False,
    },
    # ── SBS (Shopee Business Services / Warehouse) ────────────────────────
    {
        "name": "get_sbs_inventory",
        "method": "GET",
        "path": "/api/v2/sbs/get_inventory",
        "description": "Get SBS inventory",
        "family": "SBS",
        "auth_required": True,
    },
    {
        "name": "update_sbs_inventory",
        "method": "POST",
        "path": "/api/v2/sbs/update_inventory",
        "description": "Update SBS inventory",
        "family": "SBS",
        "auth_required": True,
    },
    # ── Call Endpoint (Generic Gateway) ───────────────────────────────────
    {
        "name": "call_endpoint",
        "method": "ANY",
        "path": "<any Shopee Open API path>",
        "description": "Generic gateway for any signed Open API endpoint",
        "family": "Gateway",
        "auth_required": True,
    },
]


ENDPOINT_FAMILIES: dict[str, list[dict[str, Any]]] = {}
for ep in ENDPOINT_CATALOG:
    family = ep["family"]
    if family not in ENDPOINT_FAMILIES:
        ENDPOINT_FAMILIES[family] = []
    ENDPOINT_FAMILIES[family].append(ep)


def get_endpoints_by_family(family: str) -> list[dict[str, Any]]:
    return ENDPOINT_FAMILIES.get(family, [])


def search_endpoints(query: str) -> list[dict[str, Any]]:
    q = query.lower()
    return [
        ep for ep in ENDPOINT_CATALOG
        if q in ep["name"].lower() or q in ep["description"].lower()
    ]


def list_families() -> list[str]:
    return list(ENDPOINT_FAMILIES.keys())


# Backward compatibility aliases (used by cli.py)
def list_endpoint_catalog() -> list[dict[str, Any]]:
    return [
        {
            "name": ep["name"],
            "path": ep["path"],
            "method": ep["method"],
            "auth": "access_token+shop_id" if ep["auth_required"] else "partner",
            "description": ep["description"],
            "category": ep["family"].lower().replace(" ", "_"),
            "first_class": ep["name"] in (
                "call_endpoint", "exchange_code_for_token", "refresh_token",
                "get_shop_info", "get_item_list", "get_item_detail",
                "get_item_base_info", "get_item_variations", "get_order_list",
                "get_order_detail", "get_logistics_channel_list",
                "get_tracking_number", "get_logistics_info",
                "get_return_list", "get_return_detail",
                "get_escrow_detail", "get_discount_list",
                "get_voucher_list", "get_bundle_deal_list",
                "get_add_on_deal_list", "init_video_upload",
                "get_video_upload_result", "upload_video_part",
                "complete_video_upload",
            ),
        }
        for ep in ENDPOINT_CATALOG
    ]


FAMILY_DESCRIPTIONS: dict[str, dict[str, Any]] = {
    "Auth": {"description": "Autenticacao e renovacao de tokens OAuth.", "features": ("token exchange", "refresh")},
    "Shop": {"description": "Informacoes e configuracao da loja.", "features": ("shop profile", "metadata", "holiday mode")},
    "Product": {"description": "Cadastro, estoque, preco, variantes e publicacao de itens.", "features": ("CRUD", "stock & price", "categories", "brands", "comments")},
    "GlobalProduct": {"description": "Produto global e publicacao cross-market.", "features": ("global listing", "cross-border", "variant sync")},
    "Order": {"description": "Pedidos, detalhes, status, cancelamento.", "features": ("order list", "detail", "split", "cancel")},
    "Logistics": {"description": "Envio, etiqueta, transporte, tracking.", "features": ("ship order", "awb", "tracking", "carrier")},
    "Payment": {"description": "Eventos financeiros, conciliacao, escrow.", "features": ("escrow", "wallet", "income report", "payout")},
    "Discount": {"description": "Cupons, descontos e promocoes.", "features": ("discount CRUD", "item management")},
    "Voucher": {"description": "Vouchers de desconto.", "features": ("voucher CRUD",)},
    "BundleDeal": {"description": "Bundles e combinacoes de ofertas.", "features": ("bundle CRUD",)},
    "AddOnDeal": {"description": "Add-on deals (compre junto).", "features": ("add-on CRUD",)},
    "Returns": {"description": "Devolucao, reembolso e retorno.", "features": ("return flow", "refund", "dispute")},
    "Chat": {"description": "Mensagens e atendimento.", "features": ("send message", "history", "conversations")},
    "MediaSpace": {"description": "Upload de videos (midia).", "features": ("video upload", "parts")},
    "Media": {"description": "Upload de imagens.", "features": ("image upload",)},
    "Ads": {"description": "Campanhas de anuncios.", "features": ("campaigns", "ad groups", "reports")},
    "AMS": {"description": "Afiliate Marketing Solutions.", "features": ("campaigns", "reports")},
    "AccountHealth": {"description": "Saude da conta e penalidades.", "features": ("performance", "penalties", "violations")},
    "FlashSale": {"description": "Campanhas de flash sale.", "features": ("flash sale CRUD",)},
    "TopPicks": {"description": "Colecoes Top Picks.", "features": ("top picks CRUD",)},
    "FirstMile": {"description": "Logistica de primeiro trecho.", "features": ("tracking", "waybill")},
    "Livestream": {"description": "Sessoes de live.", "features": ("session CRUD", "metrics")},
    "Video": {"description": "Videos do produto.", "features": ("video CRUD", "analytics")},
    "FBS": {"description": "Fulfillment by Shopee.", "features": ("FBS orders", "confirm", "ship")},
    "FollowPrize": {"description": "Premios de seguir loja.", "features": ("follow prize CRUD",)},
    "ShopCategory": {"description": "Categorias personalizadas da loja.", "features": ("category CRUD",)},
    "Push": {"description": "Webhooks/push notifications.", "features": ("config",)},
    "Merchant": {"description": "Informacoes do merchant.", "features": ("merchant info", "shop list")},
    "Public": {"description": "Endpoints publicos sem autenticacao.", "features": ("categories", "partner shops")},
    "SBS": {"description": "Shopee Business Services / Warehouse.", "features": ("inventory",)},
    "Gateway": {"description": "Gateway generico para qualquer endpoint.", "features": ("generic call",)},
}


def list_endpoint_families() -> list[dict[str, Any]]:
    return [
        {
            "name": family_name,
            "description": FAMILY_DESCRIPTIONS.get(family_name, {}).get("description", ""),
            "features": list(FAMILY_DESCRIPTIONS.get(family_name, {}).get("features", ())),
        }
        for family_name in ENDPOINT_FAMILIES
    ]
